// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// swap_an_edge3
NumericVector swap_an_edge3(NumericVector n1, NumericVector n2, int n_edges, int max_try);
RcppExport SEXP _wext_swap_an_edge3(SEXP n1SEXP, SEXP n2SEXP, SEXP n_edgesSEXP, SEXP max_trySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type n_edges(n_edgesSEXP);
    Rcpp::traits::input_parameter< int >::type max_try(max_trySEXP);
    rcpp_result_gen = Rcpp::wrap(swap_an_edge3(n1, n2, n_edges, max_try));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wext_swap_an_edge3", (DL_FUNC) &_wext_swap_an_edge3, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wext(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
