# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swap_an_edge3 <- function(n1, n2, n_edges, max_try) {
    .Call(`_wext_swap_an_edge3`, n1, n2, n_edges, max_try)
}

