# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Swap a single edge (method 2 in C++)
#'
#' @description Swap an edge of a bipartite graph while maintaining the
#'   partition
#'
#' @param n1,n2 the graph built as a set of two vectors with the nodes for each edge
#' @param N the number of edges to swap (one at a time)
#' @param max_try Number of times to try to find two edges to swap. If no
#'   edges are found, the program will crash with the message "Unable to swap
#'   edges"
#'
#' @return \code{n1} with nodes swapped
#'
#' @export swap_an_edgeC
swap_an_edgeC <- function(n1, n2, N, max_try) {
    .Call(`_wext_swap_an_edgeC`, n1, n2, N, max_try)
}

